class Constants:
    ENV_KEY_USER_AGENT = "LT_USER_AGENT"
    ENV_KEY_HANDSHAKE_CLIENT_VERSION = "LT_HANDSHAKE_CLIENT_VERSION"
    ENV_KEY_UPLOAD_RATE_LIMIT = "LT_UPLOAD_RATE_LIMIT"
    ENV_KEY_LT_LISTEN_INTERFACES = "LT_LISTEN_INTERFACES"
    ENV_KEY_API_SERVER_LISTEN_INTERFACES = "API_LISTEN_INTERFACES"
    ENV_KEY_PEER_ID = "LT_PEER_ID"
    ENV_KEY_DHT_BOOTSTRAP_NODES = "LT_DHT_BOOTSTRAP_NODES"
    ENV_KEY_CONNECTIONS_LIMIT = "LT_CONNECTIONS_LIMIT"